server:
  port: 8082

spring:
  application:
    name: online-market-service
  datasource:
    url: jdbc:h2:mem:online_market;DB_CLOSE_DELAY=-1
    username: root
    password: admin
    driverClassName: org.h2.Driver
    platform: online_market
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
  h2:
    console:
      enabled: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: cs545projectfeb2020@gmail.com
    password: Abcd!234
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

